import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import type { SettlementStatement } from '../../types';
import { formatINRforPDF, formatDate, formatMonth } from '../utils';
import { format } from 'date-fns';

export async function generatePDFFullSettlement(stmt: SettlementStatement, userName: string): Promise<void> {
  const doc = new jsPDF();
  const { transaction: tx, person, repayments, interestRecords } = stmt;

  // Header
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text('MoneyFlow', 14, 18);
  doc.setFontSize(13);
  doc.text('Full Settlement Statement', 14, 27);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.text(`Generated by: ${userName}  |  Date: ${format(new Date(), 'dd MMM yyyy')}`, 14, 34);

  // Transaction details
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text('Transaction Details', 14, 44);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  const details = [
    ['Person', person.name],
    ['Type', tx.type === 'borrow' ? 'Borrowed from' : 'Lent to'],
    ['Original Amount', formatINRforPDF(tx.originalAmount)],
    ['Interest Rate', `${tx.interestRate}% / month`],
    ['Start Date', formatDate(tx.startDate)],
    ['Status', tx.status],
  ];
  details.forEach(([k, v], i) => {
    doc.text(`${k}:`, 14, 52 + i * 6);
    doc.text(v, 60, 52 + i * 6);
  });

  let y = 52 + details.length * 6 + 6;

  // Repayments table
  if (repayments.length > 0) {
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.text('Repayment History', 14, y);
    y += 2;
    autoTable(doc, {
      startY: y,
      head: [['Date', 'Amount', 'Notes']],
      body: repayments.map(r => [formatDate(r.date), formatINRforPDF(r.amount), r.notes ?? '']),
      styles: { fontSize: 9 },
      headStyles: { fillColor: [59, 130, 246] },
      margin: { left: 14, right: 14 },
    });
    y = (doc as jsPDF & { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 8;
  }

  // Interest records table
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text('Month-by-Month Interest', 14, y);
  y += 2;
  autoTable(doc, {
    startY: y,
    head: [['Month', 'Principal', 'Rate', 'Interest', 'Pro-rated', 'Paid']],
    body: interestRecords.map(r => [
      formatMonth(r.month),
      formatINRforPDF(r.principalAtMonth),
      `${tx.interestRate}%`,
      formatINRforPDF(r.interestAmount),
      r.isProRated ? 'Yes' : 'No',
      r.isPaid ? '✓' : '✗',
    ]),
    styles: { fontSize: 8 },
    headStyles: { fillColor: [59, 130, 246] },
    margin: { left: 14, right: 14 },
  });
  y = (doc as jsPDF & { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 8;

  // Summary box
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text('Settlement Summary', 14, y);
  y += 6;
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  const summaryLines = [
    ['Original Amount', formatINRforPDF(tx.originalAmount)],
    ['Total Principal Repaid', formatINRforPDF(tx.originalAmount - stmt.outstandingPrincipal)],
    ['Outstanding Principal', formatINRforPDF(stmt.outstandingPrincipal)],
    ['', ''],
    ['Total Interest Accrued', formatINRforPDF(stmt.totalInterestAccrued)],
    ['Total Interest Paid', formatINRforPDF(stmt.totalInterestPaid)],
    ['Total Interest Unpaid', formatINRforPDF(stmt.totalInterestUnpaid)],
    ['', ''],
    ['TOTAL SETTLEMENT AMOUNT', formatINRforPDF(stmt.totalAmountToSettle)],
    ['Settlement Date', formatDate(stmt.settlementDate)],
  ];
  summaryLines.forEach(([k, v], i) => {
    if (!k) { y += 2; return; }
    const isBold = k === 'TOTAL SETTLEMENT AMOUNT';
    doc.setFont('helvetica', isBold ? 'bold' : 'normal');
    doc.text(`${k}:`, 14, y);
    doc.text(v, 100, y);
    y += 6;
  });

  // Footer
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(150);
  doc.text('Generated by MoneyFlow', 14, doc.internal.pageSize.height - 10);

  doc.save(`MoneyFlow_Settlement_${person.name.replace(/\s+/g, '_')}.pdf`);
}
