import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import type { InterestRecord, Person, Transaction } from '../../types';
import { formatINRforPDF, formatMonth } from '../utils';
import { format } from 'date-fns';

interface GenerateOptions {
  month: string;
  records: InterestRecord[];
  persons: Person[];
  transactions: Transaction[];
  userName: string;
}

function buildDoc(opts: GenerateOptions): jsPDF {
  const { month, records, persons, transactions, userName } = opts;
  const doc = new jsPDF();
  const monthLabel = formatMonth(month);

  // Header
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text('MoneyFlow', 14, 18);
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.text('Monthly Interest Statement', 14, 26);
  doc.setFontSize(10);
  doc.text(`Period: ${monthLabel}`, 14, 33);
  doc.text(`Generated by: ${userName}`, 14, 39);
  doc.text(`Date: ${format(new Date(), 'dd MMM yyyy')}`, 14, 45);

  let y = 55;

  // Group records by person
  const byPerson = records.reduce<Record<string, InterestRecord[]>>((acc, r) => {
    acc[r.personId] = acc[r.personId] ?? [];
    acc[r.personId].push(r);
    return acc;
  }, {});

  for (const [personId, personRecords] of Object.entries(byPerson)) {
    const person = persons.find(p => p.id === personId);
    const personName = person?.name ?? 'Unknown';

    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.text(personName, 14, y);
    y += 2;

    const rows = personRecords.map(r => {
      const tx = transactions.find(t => t.id === r.transactionId);
      return [
        tx ? formatINRforPDF(tx.originalAmount) : '-',
        tx ? `${tx.type === 'borrow' ? 'Borrow' : 'Lend'}` : '-',
        tx ? `${tx.interestRate}%/mo` : '-',
        formatINRforPDF(r.principalAtMonth),
        r.isProRated ? 'Yes' : 'No',
        formatINRforPDF(r.interestAmount),
        r.isPaid ? 'Paid' : 'Unpaid',
      ];
    });

    autoTable(doc, {
      startY: y,
      head: [['Amount', 'Type', 'Rate', 'Principal', 'Pro-rated', 'Interest', 'Status']],
      body: rows,
      styles: { fontSize: 9 },
      headStyles: { fillColor: [59, 130, 246] },
      margin: { left: 14, right: 14 },
    });

    const total = personRecords.reduce((s, r) => s + r.interestAmount, 0);
    y = (doc as jsPDF & { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 5;
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.text(`Total: ${formatINRforPDF(total)}`, 14, y);
    y += 10;
  }

  // Footer
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(150);
  doc.text('Generated by MoneyFlow', 14, doc.internal.pageSize.height - 10);

  return doc;
}

export async function generatePDFMonthlyStatement(opts: GenerateOptions): Promise<void> {
  const doc = buildDoc(opts);
  doc.save(`MoneyFlow_Statement_${opts.month}.pdf`);
}

/** Returns the PDF as a base64 string (without the data URI prefix) for email attachment */
export async function generatePDFMonthlyStatementBase64(opts: GenerateOptions): Promise<string> {
  const doc = buildDoc(opts);
  // output('datauristring') returns "data:application/pdf;base64,<data>"
  const dataUri = doc.output('datauristring');
  return dataUri.split(',')[1];
}
