import type { InterestRecord, Person, Transaction } from '../../types';
import { formatINR, formatMonth } from '../utils';
import { generatePDFMonthlyStatementBase64 } from '../pdf/monthlyStatement';

interface SendStatementOptions {
  month: string;
  toEmail: string;              // always the logged-in user's email
  persons: Person[];
  records: InterestRecord[];
  transactions: Transaction[];
  userName: string;
}

export async function sendStatementEmail(opts: SendStatementOptions): Promise<void> {
  const { month, toEmail, persons, records, transactions, userName } = opts;

  const monthLabel = formatMonth(month);

  // Build per-person sections for the HTML body
  const byPerson = records.reduce<Record<string, InterestRecord[]>>((acc, r) => {
    acc[r.personId] = acc[r.personId] ?? [];
    acc[r.personId].push(r);
    return acc;
  }, {});

  let personSections = '';
  let grandTotal = 0;

  for (const [personId, personRecords] of Object.entries(byPerson)) {
    const person = persons.find(p => p.id === personId);
    const personName = person?.name ?? 'Unknown';
    const personTotal = personRecords.reduce((s, r) => s + r.interestAmount, 0);
    grandTotal += personTotal;

    const rows = personRecords.map(r => {
      const tx = transactions.find(t => t.id === r.transactionId);
      return `
        <tr>
          <td style="padding:8px;border-bottom:1px solid #eee;">${tx ? formatINR(tx.originalAmount) : '-'}</td>
          <td style="padding:8px;border-bottom:1px solid #eee;">${tx?.interestRate ?? '-'}%/mo</td>
          <td style="padding:8px;border-bottom:1px solid #eee;">${formatINR(r.principalAtMonth)}</td>
          <td style="padding:8px;border-bottom:1px solid #eee;">${formatINR(r.interestAmount)}${r.isProRated ? ' <em style="color:#888;font-size:11px;">(pro-rated)</em>' : ''}</td>
          <td style="padding:8px;border-bottom:1px solid #eee;">${r.isPaid ? '✅ Paid' : '⬜ Unpaid'}</td>
        </tr>`;
    }).join('');

    personSections += `
      <h3 style="margin:20px 0 6px;color:#1e293b;">${personName}</h3>
      <table style="width:100%;border-collapse:collapse;">
        <thead>
          <tr style="background:#3b82f6;color:white;">
            <th style="padding:8px;text-align:left;">Amount</th>
            <th style="padding:8px;text-align:left;">Rate</th>
            <th style="padding:8px;text-align:left;">Principal</th>
            <th style="padding:8px;text-align:left;">Interest</th>
            <th style="padding:8px;text-align:left;">Status</th>
          </tr>
        </thead>
        <tbody>${rows}</tbody>
      </table>
      <p style="text-align:right;margin:6px 0 0;font-weight:600;">Subtotal: ${formatINR(personTotal)}</p>`;
  }

  const html = `
    <div style="font-family:sans-serif;max-width:640px;margin:0 auto;">
      <h2 style="color:#3b82f6;margin-bottom:4px;">MoneyFlow — Monthly Interest Statement</h2>
      <p style="color:#64748b;margin:0 0 16px;">${monthLabel}</p>
      ${personSections}
      <div style="margin-top:20px;padding:14px;background:#f1f5f9;border-radius:8px;font-size:16px;">
        <strong>Grand Total: ${formatINR(grandTotal)}</strong>
      </div>
      <p style="color:#94a3b8;font-size:12px;margin-top:24px;">
        Generated by MoneyFlow · ${userName} · PDF statement attached.
      </p>
    </div>`;

  // Generate PDF and encode as base64
  const pdfBase64 = await generatePDFMonthlyStatementBase64({
    month,
    records,
    persons,
    transactions,
    userName,
  });

  const res = await fetch('/api/send-email', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      to: toEmail,
      subject: `MoneyFlow Interest Statement — ${monthLabel}`,
      html,
      pdfBase64,
      pdfFilename: `MoneyFlow_Statement_${month}.pdf`,
    }),
  });

  if (!res.ok) {
    const err = await res.json().catch(() => ({}));
    throw new Error((err as { error?: string }).error ?? `Server error ${res.status}`);
  }
}
